######################################################################
# Automatically generated by qmake (2.01a) Tue Oct 25 21:56:59 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += doppler.h
SOURCES += main.cpp
